export const HOTEL_LIST_REQUEST = "HOTEL_LIST_REQUEST";
export const HOTEL_LIST_SUCCESS = "HOTEL_LIST_SUCCESS";
export const HOTEL_LIST_FAILURE = "HOTEL_LIST_FAILURE";

export const PLACES_REQUEST = "PLACES_REQUEST";
export const PLACES_SUCCESS = "PLACES_SUCCESS";
export const PLACES_FAILURE = "PLACES_FAILURE";

export const RESTAURANTS_LIST_REQUEST = "RESTAURANTS_LIST_REQUEST";
export const RESTAURANTS_LIST_SUCCESS = "RESTAURANTS_LIST_SUCCESS";
export const RESTAURANTS_LIST_FAILURE = "RESTAURANTS_LIST_FAILURE";

export const SIGHT_LIST_REQUEST = "SIGHT_LIST_REQUEST";
export const SIGHT_LIST_SUCCESS = "SIGHT_LIST_SUCCESS";
export const SIGHT_LIST_FAILURE = "SIGHT_LIST_FAILURE";

export const ADD_TO_BASKET_REQUEST = "ADD_TO_BASKET_REQUEST";
export const ADD_TO_BASKET_SUCCESS = "ADD_TO_BASKET_SUCCESS";
export const ADD_TO_BASKET_FAILURE = "ADD_TO_BASKET_FAILURE";


export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";

export const REMOVE_FROM_BASKET_REQUEST = "REMOVE_FROM_BASKET_REQUEST";
export const REMOVE_FROM_BASKET_SUCCESS = "REMOVE_FROM_BASKET_SUCCESS";
export const REMOVE_FROM_BASKET_FAILURE = "REMOVE_FROM_BASKET_FAILURE";

