export const HOTEL_LIST_REQUEST = "HOTEL_LIST_REQUEST"
export const HOTEL_LIST_SUCCESS = "HOTEL_LIST_SUCCESS"
export const HOTEL_LIST_FALIURE = "HOTEL_LIST_FAILURE"


export const PLACES_REQUEST = "PLACES_REQUEST";
export const PLACES_SUCCESS = "PLACES_SUCCESS";
export const PLACES_FAILURE = "PLACES_FAILURE";


