export const HOTEL_LIST_REQUEST = "HOTEL_LIST_REQUEST";
export const HOTEL_LIST_SUCCESS = "HOTEL_LIST_SUCCESS";
export const HOTEL_LIST_FAILURE = "HOTEL_LIST_FAILURE";

export const PLACES_REQUEST = "PLACES_REQUEST";
export const PLACES_SUCCESS = "PLACES_SUCCESS";
export const PLACES_FAILURE = "PLACES_FAILURE";

export const RESTAURANTS_LIST_REQUEST = "RESTAURANTS_LIST_REQUEST";
export const RESTAURANTS_LIST_SUCCESS = "RESTAURANTS_LIST_SUCCESS";
export const RESTAURANTS_LIST_FAILURE = "RESTAURANTS_LIST_FAILURE";

export const SIGHT_LIST_REQUEST = "SIGHT_LIST_REQUEST";
export const SIGHT_LIST_SUCCESS = "SIGHT_LIST_SUCCESS";
export const SIGHT_LIST_FAILURE = "SIGHT_LIST_FAILURE";
